<h3>This new page is generated by CRM/Hellocivicrm/Page/CiviHomePage.php</h3>
<h1> Hello CiviCRM </h1>
<p> My name is Kartik Kathuria and I wish to contribute and become an integral member of this organization </p>
<p> This is my first CiviCRM extension page </p>
{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>

{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>
